#!/bin/bash
#================================================
#================================================
#   O.S.      : Gnu Linux                       =
#   Author    : Cristian Pozzessere   = ilnanny =
#   D.A.Page  : http://ilnanny.deviantart.com   =
#   Github    : https://github.com/ilnanny      =
#================================================
#================================================

# ___      Alias Void


alias sv="sudo sv"
alias lvs="sudo lvs"
alias vgs="sudo vgs"
alias vgdisplay="sudo vgdisplay"
alias install="sudo xbps-install"
alias query="sudo xbps-query"
alias remove="sudo xbps-remove -R"
alias pkgdb="sudo xbps-pkgdb"
alias reconfigure="sudo xbps-reconfigure"
alias update="sudo xbps-install -Su"
alias search="sudo xbps-query -Rs"
alias ccache="xbps-remove -O"

# ___      Fine
