#!/bin/bash
#================================================
#================================================
#   O.S.      : Gnu Linux                       =
#   Author    : Cristian Pozzessere   = ilnanny =
#   D.A.Page  : http://lnanny.deviantart.com    =
#   Github    : https://github.com/ilnanny      =
#================================================
#================================================
cp -a -r /media/Dati/Git/Dotfiles/Void/void-wall.png /usr/share/backgrounds/
cp -a -r /media/Dati/Git/Dotfiles/Void/void-lxdm.png /usr/share/backgrounds/
exit



















































































































