#!/bin/bash
#================================================
#================================================
#   O.S.      : Gnu Linux                       =
#   Author    : Cristian Pozzessere   = ilnanny =
#   D.A.Page  : http://lnanny.deviantart.com    =
#   Github    : https://github.com/ilnanny      =
#================================================
#================================================
# Codici colore ANSI
#
# Black        0;30     Dark Gray     1;30
# Red          0;31     Light Red     1;31
# Green        0;32     Light Green   1;32
# Brown/Orange 0;33     Yellow        1;33
# Blue         0;34     Light Blue    1;34
# Purple       0;35     Light Purple  1;35
# Cyan         0;36     Light Cyan    1;36
# Light Gray   0;37     White         1;37
#
# Costanti
#
NONE='\033[00m'
RED='\033[01;31m'
GREEN='\033[01;32m'
YELLOW='\033[01;33m'
PURPLE='\033[01;35m'
CYAN='\033[01;36m'
WHITE='\033[01;37m'
BOLD='\033[1m'
UNDERLINE='\033[4m'
#=====================================================
#  Software per il post installazione di Void Linux  #
#=====================================================
printf "${GREEN}Aggiorno il Sistema\n"
sudo xbps-install -Su
printf "${GREEN}Installo i Software presenti nella Lista\n"
sudo xbps-install \
android-file-transfer-linux \
android-tools \
arc-theme \
bash-completion \
bleachbit \
chromium-bsu \
cmake \
conky \
curl \
deluge \
dosfstools \
ffmpeg \
file-roller \
fontconfig \
freetype \
gparted \
gtk-engine-murrine \
htop \
inetutils \
inkscape \
libreoffice \
lshw \
mtpfs \
multibootusb \
neofetch \
parted \
unzip \
volumeicon \
wget \
WoeUSB \
xdg-user-dirs \
xdg-user-dirs-gtk \
xfce-polkit \
xfce4-dev-tools \
xfce4-screenshooter \
xfce4-whiskermenu-plugin \
youtube-dl \
zip \
zenity
printf "${GREEN}Installo il tema di icone Lila HD\n"
sh /media/Dati/Git/Dotfiles/Scripts/lilahd-install.sh
exit 0

