#!/usr/bin/env bash

case $1 in
    -h|--help)
        echo -e "tint2-restart a script to restart all running instances of tint2
        \nOptions:\n\t-h --help\tshow this message and exit\n\nNo other options are supported"
        exit 0
esac

if ! [[ $(pidof tint2) ]]; then
    echo "No tint2 processes found"
    exit 0
fi

declare -A commands

while read -r pid cmd; do
    if [[ ${cmd%% *} = tint2 ]]; then
        kill "$pid"
        commands[$cmd]=1
    fi
done <<< "$(pgrep -a tint2)"

sleep 1
while read -r pid cmd; do
    if [[ ${cmd%% *} = tint2 ]]; then
        kill -KILL "$pid"
        commands[$cmd]=1
    fi
done <<< "$(pgrep -a tint2)"

sleep 1
for i in "${!commands[@]}"; do
    (setsid $i &)
    sleep 0.1
done

exit 0
