#!/bin/bash
#================================================
#================================================
#   O.S.      : Gnu Linux                       =
#   Author    : Cristian Pozzessere   = ilnanny =
#   D.A.Page  : http://ilnanny.deviantart.com    =
#   Github    : https://github.com/ilnanny      =
#================================================
#================================================
# Se la partizione di root è piena per oltre il 90%, eliminare qualsiasi directory temporanea e
# file che sono stati lasciati in /var/tmp/portage/ invece di essere cancellati.
#
# La partizione di root è su /dev/sdc2 e il comando emerge non deve essere in esecuzione.
#
# ricordati di dare i permessi 'chmod +x /etc/local.d/99delete_tmp_portage'
if [ `pgrep -c emerge` -eq 0 ] && [ `df | awk '/sda6/{print $5}' | awk -F% '{print $1}'` -gt 90 ]; then
    rm -rf/usr/tmp/portage/*
fi

exit





















































































































