#!/bin/bash
#================================================
#================================================
#   O.S.      : Gnu Linux                       =
#   Author    : Cristian Pozzessere   = ilnanny =
#   D.A.Page  : http://ilnanny.deviantart.com   =
#   Github    : https://github.com/ilnanny      =
#================================================
#  emerge --ask dcfldd
#================================================
##Backup
dcfldd if=/dev/sdc2 conv=sync,noerror bs=64K | gzip -c  > /media/Dati/backupdd_gentoo.img.gz

##Restore
# gunzip -c /media/Dati/backupdd_gentoo.img.gz | dcfldd of=/dev/sdc2


#======================================================
#======================================================
exit 0
