#!/bin/bash
#================================================
#================================================
#   O.S.      : Gnu Linux                       =
#   Author    : Cristian Pozzessere   = ilnanny =
#   D.A.Page  : http://ilnanny.deviantart.com   =
#   Github    : https://github.com/ilnanny      =
#================================================
#  emerge --ask dcfldd
#================================================
##Backup
dd if=/dev/sdc2 conv=sync,noerror bs=64K status=progress | gzip -c  > /media/Dati/backupdd_gentoo-`date +%d%m%y`.img.gz

##Restore
# gunzip -c /media/Dati/backupdd_gentoo.img.gz | dd of=/dev/sdc2  status=progress


#======================================================
#======================================================
exit 0
