#!/bin/bash
#================================================
#================================================
#   O.S.      : Gnu Linux                       =
#   Author    : Cristian Pozzessere   = ilnanny =
#   D.A.Page  : http://ilnanny.deviantart.com    =
#   Github    : https://github.com/ilnanny      =
#================================================
#================================================
# Esegui lo Script come Amministratore
set -o errexit
[[ $(whoami) == 'root' ]] || exec sudo su -c $0 root
printf " Monto le partizioni :\n"
printf " /dev/sdb1 per il /boot\n"
printf " /dev/sdb2 per il /root\n"
mount /dev/sdb2 /mnt/funtoo
mount -o remount,rw /dev/sdb2 /mnt/funtoo
mount /dev/sdb1 /mnt/funtoo/boot
mount --bind /dev /mnt/funtoo/dev
mount --make-rslave /mnt/funtoo/dev
mount --bind /proc /mnt/funtoo/proc
mount --bind /sys /mnt/funtoo/sys
mount --rbind /tmp /mnt/funtoo/tmp
env-update && source /etc/profile
chroot /mnt/funtoo /bin/bash
export PS1="\033[1;33m([chroot])\033[0m $PS1"
printf "Per installare ed aggiornare grub ,esegui :\n"
printf "grub-install /dev/sda\n"
printf "ego boot update\n"
printf "Adesso sei in chroot\n"






















































































































