#!/bin/bash
#================================================
#================================================
#   O.S.      : Gnu Linux                       =
#   Author    : Cristian Pozzessere   = ilnanny =
#   D.A.Page  : http://ilnanny.deviantart.com    =
#   Github    : https://github.com/ilnanny      =
#================================================
#================================================
set -o errexit
[[ $(whoami) == 'root' ]] || exec sudo su -c $0 root
cd /var/tmp
git clone https://github.com/funtoo/ego.git
cd ego
./ego sync
exit 

