#!/bin/bash
#================================================
#================================================
#   O.S.      : Gnu Linux                       =
#   Author    : Cristian Pozzessere   = ilnanny =
#   D.A.Page  : http://ilnanny.deviantart.com    =
#   Github    : https://github.com/ilnanny      =
#================================================
#================================================
set -o errexit
[[ $(whoami) == 'root' ]] || exec sudo su -c $0 root
grub-install /dev/sda

grub-mkconfig –o /boot/grub/grub.cfg

grub-mkconfig -o /boot/grub/grub.cfg
echo "###################################################"
echo "#               CHIUDI IL TERMINALE               #" 
echo "###################################################"
exit 0
