#!/usr/bin/env bash
#================================================
#================================================
#   O.S.      : Gnu Linux                       =
#   Author    : Cristian Pozzessere   = ilnanny =
#   D.A.Page  : http://ilnanny.deviantart.com   =
#   Github    : https://github.com/ilnanny      =
#================================================
#================================================
set -o errexit
[[ $(whoami) == 'root' ]] || exec sudo su -c $0 root
#================================================

 echo "
=========================================================
         #     Note :
         #     emerge gentoo-sources
         #     eselect kernel list
         #     eselect kernel set
========================================================="

echo "   # Copio la configurazione del kernel corrente in /root
________________________________________________________________"
 gunzip /proc/config.gz -c > /root/config

sleep 1
echo "
   # Eseguo la compilazione del Kernel
________________________________________________________________"
genkernel --makeopts=-j9 --splash --kernel-config=/root/config all

echo "
   # Aggiorno i pacchetti con i moduli del kernel
________________________________________________________________"
sleep 1
emerge -1 @module-rebuild

echo "
   # Ripulisco i vecchi file
________________________________________________________________"
sleep 1
for name in $(ls /lib/modules/ | sort -V | head -n -3); do
  rm -rf /boot/{initramfs,kernel,System.map}-genkernel-x86_64-${name:?}
  rm -rf /lib/modules/${name:?}
done

echo "
   # Aggiorno il file di configurazione di avvio
________________________________________________________________"
sleep 1
grub-mkconfig -o /boot/grub/grub.cfg
echo "
  # Nuovo Kernel aggiornato e configurato
   # Puoi riavviare il Sistema !
________________________________________________________________"



