#!/usr/bin/env bash
#================================================
#================================================
#   O.S.      : Gnu Linux                       =
#   Author    : Cristian Pozzessere   = ilnanny =
#   D.A.Page  : http://ilnanny.deviantart.com    =
#   Github    : https://github.com/ilnanny      =
#================================================
#================================================
set -o errexit
[[ $(whoami) == 'root' ]] || exec sudo su -c $0 root
echo " " >> /etc/portage/make.conf
echo "# Global USE flag declaration" >> /etc/portage/make.conf
echo "USE=\"X gtk -kde -minimal dbus jpeg lock hardened session startup-notification thunar udev -systemd -gnome alsa infinality\"" >> /etc/portage/make.conf
echo "
 gnome-base/gvfs        +udisks
 sys-auth/consolekit    +policykit
"
echo "* Desktop environment installation.."
emerge --ask "xfce-base/xfce4-meta xfce-base/thunar xfce-extra/thunar-archive-plugin xfce-extra/thunar-vcs-plugin xfce-extra/thunar-volman xfce-extra/xfce4-power-manager xfce-extra/xfce4-mount-plugin xfce-extra/xfce4-screenshooter xfce-extra/xfce4-gvfs-mount xfce-extra/xfce4-whiskermenu-plugin xfce-extra/xfce4-battery-plugin xfce-extra/xfce4-mixer"

if [[ $installTheme == "Y" ]] || [[ $installTheme == "y" ]]; then
	echo
	echo "* Installing Vertex-theme and paper-icon-theme..."

	emerge --ask "x11-themes/gtk-engines-murrine"

	# Vertex Theme by horst3180
	# https://github.com/horst3180/Vertex-theme
	git clone https://github.com/horst3180/vertex-theme --depth 1 && cd vertex-theme || exit
	./autogen.sh --prefix=/usr --disable-cinnamon --disable-gnome-shell --disable-unity
	make install
	cd ..

	# Paper-icon-theme by snwh
	# https://github.com/snwh/paper-icon-theme
	git clone https://github.com/snwh/paper-icon-theme && cd paper-icon-theme || exit
	./autogen.sh
	make -s
	make install
fi

echo "
 x11-misc/lightdm-gtk-greeter  +branding"
echo "* Display manager installation.."
emerge --ask x11-misc/lightdm-gtk-greeter
sed -i 's/xdm/lightdm/g' /etc/conf.d/xdm

# Install applications
if [[ $installApplications == "Y" ]] || [[ $installApplications == "y" ]]; then
	echo
	echo "* Beginning to emerge default program set.."

	emerge --ask "app-misc/tmux app-editors/vim app-admin/keepassx media-gfx/nomacs sys-block/gparted app-text/evince sys-apps/mlocate app-arch/p7zip"
echo "
	 sys-power/suspend +crypt
	 sys-block/gparted +ntfs
	 sys-block/gparted +fat
	 sys-block/gparted +policykit
	 app-text/poppler +cairo
"
	emerge --ask "sys-power/suspend  app-arch/file-roller net-p2p/deluge sci-calculators/galculator media-video/gnome-mplayer dev-util/geany x11-terms/guake"

echo " media-libs/libpng +apng "

	emerge --ask "www-client/firefox net-misc/vinagre app-shells/bash-completion net-misc/networkmanager net-misc/networkmanager-openvpn x11-terms/xfce4-terminal"
	
	echo "* Enabling global bash completion.."
	eselect bashcomp enable --global {0..478}
fi

cd ..
printf "\n"
printf "* Cleaning up folders for downloaded themes.. \n"
rm -rf vertex-theme/ paper-icon-theme/
