#!/usr/bin/env sh
#================================================
#================================================
#   O.S.      : Gnu Linux                       =
#   Author    : Cristian Pozzessere   = ilnanny =
#   D.A.Page  : http://ilnanny.deviantart.com   =
#   Github    : https://github.com/ilnanny      =
#================================================
#================================================
# Terminate already running conky instances
killall -q conky

# Wait until the processes have been shut down
while pgrep -x conky > /dev/null; do sleep 1; done

# Launch conky

conky &

echo "Conky launched..."
