#! /bin/bash
#================================================
#================================================
#   O.S.      : Gnu Linux                       =
#   Author    : Cristian Pozzessere   = ilnanny =
#   D.A.Page  : http://ilnanny.deviantart.com   =
#   Github    : https://github.com/ilnanny      =
#================================================
#================================================
FILENAME=`date +%Y-%m-%d-%H-%M-%S`.png
scrot -d 0.1 "$FILENAME" -e 'xclip -selection clipboard -t image/png $f && mv $f ~/Pictures/screenshots/'
notify-send "📷 Saved screenshot as $FILENAME"
