#!/bin/bash
#================================================
#================================================
#   O.S.      : Gnu Linux                       =
#   Author    : Cristian Pozzessere   = ilnanny =
#   D.A.Page  : http://lnanny.deviantart.com    =
#   Github    : https://github.com/ilnanny      =
#================================================
#================================================
# Codici colore ANSI
#
# Black        0;30     Dark Gray     1;30
# Red          0;31     Light Red     1;31
# Green        0;32     Light Green   1;32
# Brown/Orange 0;33     Yellow        1;33
# Blue         0;34     Light Blue    1;34
# Purple       0;35     Light Purple  1;35
# Cyan         0;36     Light Cyan    1;36
# Light Gray   0;37     White         1;37
#
# Costanti
#
NONE='\033[00m'
RED='\033[01;31m'
GREEN='\033[01;32m'
YELLOW='\033[01;33m'
PURPLE='\033[01;35m'
CYAN='\033[01;36m'
WHITE='\033[01;37m'
BOLD='\033[1m'
UNDERLINE='\033[4m'
printf "${YELLOW}#=====================================================\n"
printf "${RED}#  Softwares per il post installazione di slackware  #\n"
printf "${YELLOW}#=====================================================\n"
printf "${GREEN}Aggiorno il Sistema\n"
sudo sudo slapt-get -u
sudo slapt-get --upgrade
sudo slackpkg update
printf "${GREEN}Installo i Software presenti nella Lista\n"
slapt-get -i \
slackpkg \
android-tools \
arc-theme \
bash-completion \
cmake \
conky \
curl \
deluge \
dosfstools \
ffmpeg \
ntfs-3g \
os-prober \
parted \
fontconfig \
freetype \
geany \
GConf \
git \
gparted \
gvfs \
htop \
inkscape \
iw \
lame \
leafpad \
libgksu \
arc \
wicd \
lshw \
make \
mtpfs \
nano \
thunar-archive-plugin \
thunar-media-tags-plugin \
usbutils \
vlc \
volumeicon \
vte3 \
wget \
xdg-user-dirs \
xfce4-dev-tools \
xfce4-screenshooter \
xfce4-whiskermenu-plugin \
youtube-dl \
zenity
printf "${GREEN}Installo il tema di icone Lila HD\n"
sh /media/Dati/Git/Dotfiles/Scripts/lilahd-install
sh /media/Dati/Git/Dotfiles/Scripts/arch-theme

exit 0

