#!/bin/bash
#================================================
#================================================
#   O.S.      : Gnu Linux                       =
#   Author    : Cristian Pozzessere   = ilnanny =
#   D.A.Page  : http://ilnanny.deviantart.com   =
#   Github    : https://github.com/ilnanny      =
#================================================
#  Source list 3rd e gpg-key debian buster                                 =
#================================================
#Imposta l'utente Root
set -o errexit
[[ $(whoami) == 'root' ]] || exec sudo su -c $0 root
#
#
echo "Installo https-transfert:"
sleep 2
apt install curl wget apt-transport-https dirmngr
#==================================================================================================

echo "Creo il nuovo file Sources List:"
sleep 2
touch /etc/apt/sources.list.d/3rd.list
cat <<'EOF' > /etc/apt/sources.list.d/3rd.list
# _____________________________________________________________________________
#
#                   Repository Ufficiali Debian Stable
# _____________________________________________________________________________

#deb http://deb.debian.org/debian/ stable main contrib non-free
#deb-src http://deb.debian.org/debian/ stable main contrib non-free

#deb http://deb.debian.org/debian/ stable-updates main contrib non-free
#deb-src http://deb.debian.org/debian/ stable-updates main contrib non-free

#deb http://deb.debian.org/debian-security stable/updates main
#deb-src http://deb.debian.org/debian-security stable/updates main

#deb http://ftp.debian.org/debian buster-backports main
#deb-src http://ftp.debian.org/debian buster-backports main

# _____________________________________________________________________________
#
#                         Repository di Terze Parti
# _____________________________________________________________________________


# →→→  Debian Multimedia
deb [arch=amd64,i386] https://www.deb-multimedia.org buster main non-free

# →→→  Google Chrome Browser
deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main

# →→→  Liveconfig
deb http://repo.liveconfig.com/debian/ main main

# →→→  MariaDB
deb [arch=i386,amd64] http://mirror.23media.de/mariadb/repo/10.2/debian stretch main
deb-src [arch=i386,amd64] http://mirror.23media.de/mariadb/repo/10.2/debian stretch main

# →→→  NodeJs
deb https://deb.nodesource.com/node_12.x buster main
deb-src https://deb.nodesource.com/node_12.x buster main

# →→→  Opera Browser
deb http://deb.opera.com/opera-stable/ stable non-free

# →→→  Skype
deb [arch=amd64] https://repo.skype.com/deb stable main

# →→→  Spotify
deb http://repository.spotify.com stable non-free

# →→→  Steam
deb [arch=i386,amd64] http://repo.steampowered.com/steam/ precise steam

# →→→  Teamviewer
deb http://linux.teamviewer.com/deb stable main

# →→→  Virtualbox
deb [arch=i386,amd64] http://download.virtualbox.org/virtualbox/debian buster contrib

# →→→  Wine
deb [arch=i386] https://dl.winehq.org/wine-builds/debian/ buster main

# →→→  Yarn
deb https://dl.yarnpkg.com/debian/ stable main

# _____________________________________________________________________________
EOF

#==================================================================================================
echo " Aggiungo le Chiavi GPG :"
sleep 3

wget http://www.deb-multimedia.org/pool/main/d/deb-multimedia-keyring/deb-multimedia-keyring_2016.8.1_all.deb && dpkg -i deb-multimedia-keyring_2016.8.1_all.deb

wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | apt-key add -

apt-key adv --keyserver ha.pool.sks-keyservers.net --recv-keys D530E028F59EAE4D

wget -O - https://www.liveconfig.com/liveconfig.key | apt-key add -

wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | apt-key add -

apt-key adv --recv-keys --keyserver keyserver.ubuntu.com 0xF1656F24C74CD1D8

curl -s https://deb.nodesource.com/gpgkey/nodesource.gpg.key | apt-key add -

wget -O - https://deb.opera.com/archive.key | apt-key add -

apt-key adv --keyserver ha.pool.sks-keyservers.net --recv-keys 1F3045A5DF7587C3

apt-key adv --keyserver ha.pool.sks-keyservers.net --recv-keys 4773BD5E130D1D45

apt-key adv --keyserver keyserver.ubuntu.com --recv-keys F24AEA9FB05498B7

wget -O - https://download.teamviewer.com/download/linux/signature/TeamViewer2017.asc | apt-key add -

apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 72B97FD1D9672C93

wget -q https://www.virtualbox.org/download/oracle_vbox_2016.asc -O- | sudo apt-key add -

wget -q https://www.virtualbox.org/download/oracle_vbox.asc -O- | sudo apt-key add -

wget -nc https://dl.winehq.org/wine-builds/winehq.key && apt-key add winehq.key && rm winehq.key

curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
echo " Aggiorno le Liste "
sleep 3
apt update
apt dist-upgrade
echo " I Repository di Terze Parti sono stati aggiunti
       e configurati correttamente !"
sleep 3


exit

