#!/bin/bash
su -c "
cp /home/ilnanny/.bashrc /home/ilnanny/.dotfiles/Debian/.bashrc
cp /home/ilnanny/.xinitrc /home/ilnanny/.dotfiles/Debian/.xinitrc
cp /home/ilnanny/.xresources /home/ilnanny/.dotfiles/Debian/.xresources
cp -r -a  /home/ilnanny/.config/bleachbit /home/ilnanny/.dotfiles/Debian/.config/
cp -r -a  /home/ilnanny/.config/catfish /home/ilnanny/.dotfiles/Debian/.config/
cp -r -a  /home/ilnanny/.config/compton.conf /home/ilnanny/.dotfiles/Debian/.config/
cp -r -a  /home/ilnanny/.config/deadbeef /home/ilnanny/.dotfiles/Debian/.config/
cp -r -a  /home/ilnanny/.config/deluge /home/ilnanny/.dotfiles/Debian/.config/
cp -r -a  /home/ilnanny/.config/fbpanel /home/ilnanny/.dotfiles/Debian/.config/
cp -r -a  /home/ilnanny/.config/fontforge /home/ilnanny/.dotfiles/Debian/.config/
cp -r -a  /home/ilnanny/.config/geany /home/ilnanny/.dotfiles/Debian/.config/
cp -r -a  /home/ilnanny/.config/gpicview /home/ilnanny/.dotfiles/Debian/.config/
cp -r -a  /home/ilnanny/.config/gtk-2.0 /home/ilnanny/.dotfiles/Debian/.config/
cp -r -a  /home/ilnanny/.config/gtk-3.0 /home/ilnanny/.dotfiles/Debian/.config/
cp -r -a  /home/ilnanny/.config/htop /home/ilnanny/.dotfiles/Debian/.config/
cp -r -a  /home/ilnanny/.config/leafpad /home/ilnanny/.dotfiles/Debian/.config/
cp -r -a  /home/ilnanny/.config/libfm /home/ilnanny/.dotfiles/Debian/.config/
cp -r -a  /home/ilnanny/.config/lxpanel /home/ilnanny/.dotfiles/Debian/.config/
cp -r -a  /home/ilnanny/.config/lxqt /home/ilnanny/.dotfiles/Debian/.config/
cp -r -a  /home/ilnanny/.config/lxsession /home/ilnanny/.dotfiles/Debian/.config/
cp -r -a  /home/ilnanny/.config/lxtask.conf /home/ilnanny/.dotfiles/Debian/.config/
cp -r -a  /home/ilnanny/.config/lxterminal /home/ilnanny/.dotfiles/Debian/.config/
cp -r -a  /home/ilnanny/.config/menus /home/ilnanny/.dotfiles/Debian/.config/
cp -r -a  /home/ilnanny/.config/menutray /home/ilnanny/.dotfiles/Debian/.config/
cp -r -a  /home/ilnanny/.config/neofetch /home/ilnanny/.dotfiles/Debian/.config/
cp -r -a  /home/ilnanny/.config/nitrogen /home/ilnanny/.dotfiles/Debian/.config/
cp -r -a  /home/ilnanny/.config/nomacs /home/ilnanny/.dotfiles/Debian/.config/
cp -r -a  /home/ilnanny/.config/obbrowser /home/ilnanny/.dotfiles/Debian/.config/
cp -r -a  /home/ilnanny/.config/obmenu-generator /home/ilnanny/.dotfiles/Debian/.config/
cp -r -a  /home/ilnanny/.config/openbox /home/ilnanny/.dotfiles/Debian/.config/
cp -r -a  /home/ilnanny/.config/pcmanfm /home/ilnanny/.dotfiles/Debian/.config/
cp -r -a  /home/ilnanny/.config/pcmanfm-qt /home/ilnanny/.dotfiles/Debian/.config/
cp -r -a  /home/ilnanny/.config/pnmixer /home/ilnanny/.dotfiles/Debian/.config/
cp -r -a  /home/ilnanny/.config/polybar /home/ilnanny/.dotfiles/Debian/.config/
cp -r -a  /home/ilnanny/.config/sakura /home/ilnanny/.dotfiles/Debian/.config/
cp -r -a  /home/ilnanny/.config/slim.conf /home/ilnanny/.dotfiles/Debian/.config/
cp -r -a  /home/ilnanny/.config/terminator /home/ilnanny/.dotfiles/Debian/.config/
cp -r -a  /home/ilnanny/.config/Thunar /home/ilnanny/.dotfiles/Debian/.config/
cp -r -a  /home/ilnanny/.config/tint2 /home/ilnanny/.dotfiles/Debian/.config/
cp -r -a  /home/ilnanny/.config/Trolltech.conf /home/ilnanny/.dotfiles/Debian/.config/
cp -r -a  /home/ilnanny/.config/user-dirs.locale /home/ilnanny/.dotfiles/Debian/.config/
cp -r -a  /home/ilnanny/.config/xfce4 /home/ilnanny/.dotfiles/Debian/.config/
cp -r -a  /home/ilnanny/.config/xfce4-session /home/ilnanny/.dotfiles/Debian/.config/
cp -r -a  /home/ilnanny/.config/yad.conf /home/ilnanny/.dotfiles/Debian/.config/
cp -r -a  /home/ilnanny/.config/youtube-viewer /home/ilnanny/.dotfiles/Debian/.config/
cp -r -a /etc/apt/ /home/ilnanny/.dotfiles/Debian/
cp -r -a /etc/sudoers /home/ilnanny/.dotfiles/Debian/
cp -r -a /etc/fstab /home/ilnanny/.dotfiles/Debian/"
exit 0
