#!/bin/sh
#
# sinstallpkg created by ingemar Karlsson <ingemar@ingk.se>
#
# sinstallpkg is a script for installing SalixOS/Slackware packages by Thunar custom actions.
# To use it make a custom action in Thunar.
# command: "gksu sinstallpkg %f"
# icon: system-software-installation
# Pattern: .tgz; *.txz
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# dependencies
#	bash
#	zenity
#	spkg-pkgtools

strTITLE="`basename $0`"
strVER="0.0.1"

strINFO_SUCCESS="Package installed"
strINFO_FAILED="Error installing package"
strERROR="ERROR"
strINSTALL="Installing "
strROOT="$strTITLE needs to run as root!"

case $LANG in
    sv* )
	strINFO_SUCCESS="Paket \"$1\" installerad."
	strINFO_FAILED="Fel vid installation av \"$1\" paketet!"
	strERROR="FEL"
	strINSTALL="Installerar "
	strROOT="$strTITLE behöver köras som root!"
esac

# Test to see it is run as root
if [ $UID = 0 ]; then
	# If run as root install pakage
	/sbin/installpkg $1 | $(zenity --progress --title="$strTITLE $strVER" --text="$strINSTALL $1" --pulsate --auto-close)
	# Test if success
	if [ $? -eq 0 ]; then
		zenity --info --text="$strINFO_SUCCESS"
	else
		zenity --info --text="$strINFO_FAILED" --title="$strERROR $strTITLE $strVER"
	fi
# Not root user
else
	zenity --error --title="$strERROR: $strTITLE $strVER" --text="$strROOT"
fi
