#!/bin/bash
#================================================
#   O.S.      : Gnu Linux                       =
#   Author    : Cristian Pozzessere   = ilnanny =
#   D.A.Page  : http://ilnanny.deviantart.com   =
#   Github    : https://github.com/ilnanny      =
#================================================
echo "                        Copy      and     Paste   😂                       "
echo ""
echo "    ❤️   ❣️   ✔️  ☑️   ⚪ ️  ⚫️   ▪️   ▫️  ◾️  ◽️  ◼️  ✖️  ™️  ©️   ®️ ‍ ♀  ‍♂️   ♾    ‍☠️   ☸️"
echo ""
echo "    ⏏️  ▶️  ◀️  ➡️  ⬅️  ⬆️  ⬇️  ☢️  ☣️  ✡️ ☯️ ☦️  ♈️ ♉️ ♊️ ♋️ ♌️ ♍️ ♎️ ♏️  ♐️  ♑️ ♒️ ♓️ ⚛️"
echo ""
echo " ️   ♣️   ♥️  ♦️  🃏  ✖️  ↗️  ↘️  ↙  ↖️  ↕️  ↔️  ↪️  ↩️  ⤴️  ⤵️  ⚠️  ⚜️  ♻️  ❇️  ✳️   Ⓜ️  ☮️  ✝️  ☪️"
echo ""
echo "    😀  😁  😂  😃  😄  😅  😆  😉  😊  😋  😎  😍  😘  😗  😙  😚  ☺️  😐   😑"
echo ""
echo "    😯  😪  😫  😴  😌  😛  😜  😝  😒   😓  😔  😕  🙃  😲  ☹️  😖  😞  😟  😢"
echo ""
echo "    😩  😰  😱  😳  😵  😡  😠  😷  😇  😈  😺  😸  😹  😻  😼  😽  🙀  😿  😾"
echo ""
echo "                      😭  😦  😧  😨  😶  😏  😣  😥  😮                  "
echo ""
echo ""
echo ""
echo "             Close    your   Terminal   Emulation  to   Exit          "

