#!/bin/bash
#================================================
#================================================
#   O.S.      : Gnu Linux                       =
#   Author    : Cristian Pozzessere   = ilnanny =
#   D.A.Page  : http://ilnanny.deviantart.com   =
#   Github    : https://github.com/ilnanny      =
#================================================
#================================================
#  ===  ===  ===  ===  ===  ===  ===  ===  ===
#Change dimension ,eg. from 64 to 96 pixel:
#  ===  ===  ===  ===  ===  ===  ===  ===  ===
# sed -i "s/'   ='/'   ='/g" *.svg
# sed -i "s/64px/96px/g" *.svg
#  ===  ===  ===  ===  ===  ===  ===  ===  ===
#  ===  ===  ===  ===  ===  ===  ===  ===  ===
#Change color ,eg.from standard to ...:
#e0a55a   standard-color
#  ===  ===  ===  ===  ===
#359bfa   blue
# sed -i "s/#e0a55a/#359bfa/g" *.svg
# 2e8d13   green
 #  sed -i "s/#e0a55a/#2e8d13/g" *.svg
# dec993   kaki
#  sed -i "s/#e0a55a/#dec993/g" *.svg
# c0c0c0ff   ligth-gray
# sed -i "s/#e0a55a/#c0c0c0ff/g" *.svg
# 4E5558   dark
#  sed -i "s/#e0a55a/#4E5558/g" *.svg
# C094C0   purple
# sed -i "s/#e0a55a/#C094C0/g" *.svg
#  ===  ===  ===  ===  ===  ===  ===  ===  ===
#  ===  ===  ===  ===  ===  ===  ===  ===  ===
#evolvere
# sed -i "s/#f4ae3f/#3faff4/g" *.svg
# sed -i "s/#da8c1f/#1f92da/g" *.svg
# sed -i "s/#8c3d00/#00568c/g" *.svg
# sed -i "s/#b54f00/#5b5b5b/g" *.svg

exit 0

