#!/bin/bash
#================================================
#================================================
#   O.S.      : Gnu Linux                       =
#   Author    : Cristian Pozzessere   = ilnanny =
#   D.A.Page  : http://ilnanny.deviantart.com   =
#   Github    : https://github.com/ilnanny      =
#================================================
# script di avvio per conky
#================================================
sleep 1
conky -c /home/$USER/.conky/Lila-HD/.conkyrc
#sleep 5
#conky -c /home/$USER/.conky/Arkitekt/.conkyrc
#sleep 8
#conky -c /home/$USER/.conky/Drex64/.conkyrc
#sleep 10
#conky -c /home/$USER//Brown-Vert/.conkyrc
#sleep 15
#conky -c /home/$USER/.conky/Brown-Oriz/.conkyrc

exit
