#!/bin/bash
#================================================
#================================================
#   O.S.      : Gnu Linux                       =
#   Author    : Cristian Pozzessere   = ilnanny =
#   D.A.Page  : http://ilnanny.deviantart.com   =
#   Github    : https://github.com/ilnanny      =
#================================================
#================================================
cp -r -a  ~/.fonts ~/.dotfiles/fonts
cp -r -a  ~/.conky ~/.dotfiles/conky
cp ~/.bashrc ~/.dotfiles/bashrc
cp ~/.xinitrc ~/.dotfiles/xinitrc
cp ~/.xresources ~/.dotfiles/xresources
cp -r -a  ~/Scripts ~/.dotfiles/
cp -r -a  ~/.config/dotfiles ~/.dotfiles/dotfiles
cp -r -a  ~/.config/bleachbit ~/.dotfiles/.config/
cp -r -a  ~/.config/catfish ~/.dotfiles/.config/
#cp -r -a  ~/.config/compiz ~/.dotfiles/.config/
#cp -r -a  ~/.config/compton.conf ~/.dotfiles/.config/
cp -r -a  ~/.config/deadbeef ~/.dotfiles/.config/
cp -r -a  ~/.config/deluge ~/.dotfiles/.config/
#cp -r -a  ~/.config/enchant ~/.dotfiles/.config/
#cp -r -a  ~/.config/fbpanel ~/.dotfiles/.config/
cp -r -a  ~/.config/fontforge ~/.dotfiles/.config/
cp -r -a  ~/.config/geany ~/.dotfiles/.config/
#cp -r -a  ~/.config/ghb ~/.dotfiles/.config/
#cp -r -a  ~/.config/gmpc ~/.dotfiles/.config/
cp -r -a  ~/.config/gpicview ~/.dotfiles/.config/
cp -r -a  ~/.config/gtk-2.0 ~/.dotfiles/.config/
cp -r -a  ~/.config/gtk-3.0 ~/.dotfiles/.config/
cp -r -a  ~/.config/htop ~/.dotfiles/.config/
cp -r -a  ~/.config/leafpad ~/.dotfiles/.config/
#cp -r -a  ~/.config/libfm ~/.dotfiles/.config/
#cp -r -a  ~/.config/lxpanel ~/.dotfiles/.config/
#cp -r -a  ~/.config/lxqt ~/.dotfiles/.config/
#cp -r -a  ~/.config/lxsession ~/.dotfiles/.config/
#cp -r -a  ~/.config/lxtask.conf ~/.dotfiles/.config/
#cp -r -a  ~/.config/lxterminal ~/.dotfiles/.config/
cp -r -a  ~/.config/menus ~/.dotfiles/.config/
#cp -r -a  ~/.config/menutray ~/.dotfiles/.config/
cp -r -a  ~/.config/neofetch ~/.dotfiles/.config/
cp -r -a  ~/.config/nitrogen ~/.dotfiles/.config/
cp -r -a  ~/.config/nomacs ~/.dotfiles/.config/
#cp -r -a  ~/.config/obbrowser ~/.dotfiles/.config/
cp -r -a  ~/.config/obmenu-generator ~/.dotfiles/.config/
cp -r -a  ~/.config/openbox ~/.dotfiles/.config/
cp -r -a  ~/.config/pcmanfm ~/.dotfiles/.config/
#cp -r -a  ~/.config/pcmanfm-qt ~/.dotfiles/.config/
#cp -r -a  ~/.config/pnmixer ~/.dotfiles/.config/
#cp -r -a  ~/.config/polybar ~/.dotfiles/.config/
#cp -r -a  ~/.config/sakura ~/.dotfiles/.config/
cp -r -a  ~/.config/slim.conf ~/.dotfiles/.config/
cp -r -a  ~/.config/terminator ~/.dotfiles/.config/
#cp -r -a  ~/.config/terminology ~/.dotfiles/.config/
cp -r -a  ~/.config/Thunar ~/.dotfiles/.config/
#cp -r -a  ~/.config/tint2 ~/.dotfiles/.config/
cp -r -a  ~/.config/Trolltech.conf ~/.dotfiles/.config/
cp -r -a  ~/.config/user-dirs.locale ~/.dotfiles/.config/
cp -r -a  ~/.config/xfce4 ~/.dotfiles/.config/
cp -r -a  ~/.config/xfce4-session ~/.dotfiles/.config/
cp -r -a  ~/.config/yad.conf ~/.dotfiles/.config/
cp -r -a  ~/.config/youtube-viewer ~/.dotfiles/.config/
exit 0
