#!/bin/bash
#================================================
#================================================
#   O.S.      : Gnu Linux                       =
#   Author    : Cristian Pozzessere   = ilnanny =
#   D.A.Page  : http://ilnanny.deviantart.com   =
#   Github    : https://github.com/ilnanny      =
#================================================
# Backup dei miei file in 'dotfiles'
#================================================
NONE='\033[00m'
RED='\033[01;31m'
GREEN='\033[01;32m'
YELLOW='\033[01;33m'
PURPLE='\033[01;35m'
CYAN='\033[01;36m'
BOLD='\033[1m'
#
set -o errexit
[[ $(whoami) == 'root' ]] || exec sudo su -c $0 root
##====================================================
printf "${RED}Creo un backup delle cartelle e dei file principali della home \n"
printf "${CYAN}__________________________________________________________________ \n"
sleep 1 &&
#Cartella config
cp -a -r /home/ilnanny/.config/Thunar /media/Dati/Git/Dotfiles/home/.config/
cp -a -r /home/ilnanny/.config/bleachbit /media/Dati/Git/Dotfiles/home/.config/
cp -a -r /home/ilnanny/.config/deluge /media/Dati/Git/Dotfiles/home/.config/
cp -a -r /home/ilnanny/.config/geany /media/Dati/Git/Dotfiles/home/.config/
cp -a -r /home/ilnanny/.config/gtk-2.0 /media/Dati/Git/Dotfiles/home/.config/
cp -a -r /home/ilnanny/.config/gtk-3.0 /media/Dati/Git/Dotfiles/home/.config/
cp -a -r /home/ilnanny/.config/jgmenu /media/Dati/Git/Dotfiles/home/.config/
cp -a -r /home/ilnanny/.config/neofetch /media/Dati/Git/Dotfiles/home/.config/
cp -a -r /home/ilnanny/.config/nvim /media/Dati/Git/Dotfiles/home/.config/
cp -a -r /home/ilnanny/.config/obmenu-generator /media/Dati/Git/Dotfiles/home/.config/
cp -a -r /home/ilnanny/.config/openbox /media/Dati/Git/Dotfiles/home/.config/
cp -a -r /home/ilnanny/.config/pnmixer /media/Dati/Git/Dotfiles/home/.config/
cp -a -r /home/ilnanny/.config/polybar /media/Dati/Git/Dotfiles/home/.config/
cp -a -r /home/ilnanny/.config/pulse /media/Dati/Git/Dotfiles/home/.config/
cp -a -r /home/ilnanny/.config/qalculate /media/Dati/Git/Dotfiles/home/.config/
cp -a -r /home/ilnanny/.config/ranger /media/Dati/Git/Dotfiles/home/.config/
cp -a -r /home/ilnanny/.config/rofi /media/Dati/Git/Dotfiles/home/.config/
cp -a -r /home/ilnanny/.config/sakura /media/Dati/Git/Dotfiles/home/.config/
cp -a -r /home/ilnanny/.config/skippy-xd /media/Dati/Git/Dotfiles/home/.config/
cp -a -r /home/ilnanny/.config/vlc /media/Dati/Git/Dotfiles/home/.config/
cp -a -r /home/ilnanny/.config/xfce4 /media/Dati/Git/Dotfiles/home/.config/
cp -a -r /home/ilnanny/.config/youtube-dlg /media/Dati/Git/Dotfiles/home/.config/
cp -a -r /home/ilnanny/.config/tint2 /media/Dati/Git/Dotfiles/home/.config/
cp -a -r /home/ilnanny/.config/gtk-3.0/ /media/Dati/Git/Dotfiles/home/.config/
#
cp -a /home/ilnanny/.config/compton.conf /media/Dati/Git/Dotfiles/home/.config/
cp -a /home/ilnanny/.config/greenclip.cfg /media/Dati/Git/Dotfiles/home/.config/
cp -a /home/ilnanny/.config/user-dirs.dirs /media/Dati/Git/Dotfiles/home/.config/
cp -a /home/ilnanny/.config/user-dirs.locale /media/Dati/Git/Dotfiles/home/.config/
cp -a /home/ilnanny/.config/.vimrc /media/Dati/Git/Dotfiles/home/.config/
#Cartelle
cp -a -r /home/ilnanny/.conky /media/Dati/Git/Dotfiles/home/
cp -a -r /home/ilnanny/.fonts /media/Dati/Git/Dotfiles/home/
cp -a -r /home/ilnanny/.vim  /media/Dati/Git/Dotfiles/home/
cp -a -r /home/ilnanny/.icons /media/Dati/Git/Dotfiles/home/
#cp -a -r /home/ilnanny/.local /media/Dati/Git/Dotfiles/home/
#Files
cp -a /home/ilnanny/.Xdefaults /media/Dati/Git/Dotfiles/home/
cp -a /home/ilnanny/.Xresources /media/Dati/Git/Dotfiles/home/
cp -a /home/ilnanny/.asoundrc /media/Dati/Git/Dotfiles/home/
cp -a /home/ilnanny/.bash_logout /media/Dati/Git/Dotfiles/home/
cp -a /home/ilnanny/.bash_profile /media/Dati/Git/Dotfiles/home/
cp -a /home/ilnanny/.bashrc /media/Dati/Git/Dotfiles/home/
cp -a /home/ilnanny/.config /media/Dati/Git/Dotfiles/home/
cp -a /home/ilnanny/.conky /media/Dati/Git/Dotfiles/home/
cp -a /home/ilnanny/.conkyrc /media/Dati/Git/Dotfiles/home/
cp -a /home/ilnanny/.dmrc /media/Dati/Git/Dotfiles/home/
cp -a /home/ilnanny/.face /media/Dati/Git/Dotfiles/home/
cp -a /home/ilnanny/.gitconfig /media/Dati/Git/Dotfiles/home/
cp -a /home/ilnanny/.glivrc /media/Dati/Git/Dotfiles/home/
cp -a /home/ilnanny/.vim /media/Dati/Git/Dotfiles/home/
cp -a /home/ilnanny/.vimrc /media/Dati/Git/Dotfiles/home/
cp -a /home/ilnanny/.xinitrc /media/Dati/Git/Dotfiles/home/
#________________________________________________________________________________
printf "${YELLOW}Fatto !.. puoi chiudere il terminale e continuare il tuo lavoro .\n"
exit
