#!/bin/bash
#================================================
#================================================
#   O.S.      : Gnu Linux                       =
#   Author    : Cristian Pozzessere   = ilnanny =
#   D.A.Page  : http://ilnanny.deviantart.com   =
#   Github    : https://github.com/ilnanny      =
#================================================
# Recupero dei miei file dal backup 'dotfiles'
#================================================
NONE='\033[00m'
RED='\033[01;31m'
GREEN='\033[01;32m'
YELLOW='\033[01;33m'
PURPLE='\033[01;35m'
CYAN='\033[01;36m'
BOLD='\033[1m'
#
set -o errexit
[[ $(whoami) == 'root' ]] || exec sudo su -c $0 root
##============================================================
printf "${BOLD}${RED}Creo i collegamenti permanenti in home\n"
#___________________________________________________________
rm -r /home/ilnanny/Modelli
rm -r  /home/ilnanny/Musica
rm -r  /home/ilnanny/Immagini
rm -r  /home/ilnanny/Documenti
sleep 1 &&
ln -s /media/Dati/Git/Dotfiles/home/Modelli/ /home/ilnanny/Modelli
ln -s /media/Dati/Musica/ /home/ilnanny/Musica
ln -s /media/Dati/01-download/Artworks-1/ /home/ilnanny/Immagini
ln -s /media/Dati/Git/Dotfiles/01-Files/Wiki/ /home/ilnanny/Documenti
ln -s  /home/ilnanny/bin
#___________________________________________________________
printf "${CYAN}Ripristino Cartelle e files da Dotfiles:\n"
#cartelle
sleep 1 &&
cp -a -r /media/Dati/Git/Dotfiles/home/.config /home/ilnanny/
cp -a -r /media/Dati/Git/Dotfiles/home/.conky /home/ilnanny/
cp -a -r /media/Dati/Git/Dotfiles/home/.fonts /home/ilnanny/
cp -a -r /media/Dati/Git/Dotfiles/home/.vim /home/ilnanny/
cp -a -r /media/Dati/Git/Dotfiles/home/.icons/ /home/ilnanny/
cp -a -r /media/Dati/Git/Dotfiles/home/.local/ /home/ilnanny/
#files
cd /media/Dati/Git/Dotfiles/home/
sleep 1 &&
cp -a .Xdefaults /home/ilnanny/
cp -a .Xresources /home/ilnanny/
cp -a .asoundrc /home/ilnanny/
cp -a .bash_logout /home/ilnanny/
cp -a .bash_profile /home/ilnanny/
cp -a .bashrc /home/ilnanny/
cp -a .conkyrc /home/ilnanny/
cp -a .dmrc /home/ilnanny/
cp -a .face /home/ilnanny/
cp -a .gitconfig /home/ilnanny/
cp -a .glivrc /home/ilnanny/
cp -a .vimrc /home/ilnanny/
cp -a .xinitrc /home/ilnanny/
printf "${CYAN}Ripristino Le configurazione principali in /root:\n"
#root
sleep 1 &&
cp -a -r /media/Dati/Git/Dotfiles/home/.config /root/
#________________________________________________________________________________
printf "${YELLOW}Assegno i permessi di scrittura/lettura ed il proprietario ai file copiati \n"
sleep 1 &&
chown -R ilnanny:ilnanny /home/ilnanny && chmod -R 775 /home/ilnanny
chown -R root /root && chmod -R 775 /root
printf "${RED}Fatto !.. puoi chiudere il terminale e continuare il tuo lavoro .\n"
printf "${YELLOW}___________________________________________________________________\n"
exit
