#!/bin/bash
#================================================
#================================================
#   O.S.      : Gnu Linux                       =
#   Author    : Cristian Pozzessere   = ilnanny =
#   D.A.Page  : http://ilnanny.deviantart.com   =
#   Github    : https://github.com/ilnanny      =
#================================================
#dipende : xdg-user-dirs xdg-user-dirs-gtk
#================================================
echo "###################################################"
echo "#                                                 #"
echo "#         AGGIORNO IL NOME DELLE CARTELLE         #"
echo "#                                                 #"
echo "###################################################"
xdg-user-dirs-gtk-update
echo "###################################################"
echo "#                                                 #"
echo "#             FATTO; CHIUDI IL TERMINALE          #"
echo "#                                                 #"
echo "###################################################"
exit 4
