#!/bin/bash
#================================================
#================================================
#   O.S.      : Gnu Linux                       =
#   Author    : Cristian Pozzessere   = ilnanny =
#   D.A.Page  : http://ilnanny.deviantart.com    =
#   Github    : https://github.com/ilnanny      =
#================================================
#================================================
sudo grub-install /dev/sda

#sudo grub-mkconfig –o /boot/grub/grub.cfg

sudo grub-mkconfig -o /boot/grub/grub.cfg
exit 0




















































































































