#!/bin/bash
#================================================
#================================================
#   O.S.      : Gnu Linux                       =
#   Author    : Cristian Pozzessere   = ilnanny =
#   D.A.Page  : http://ilnanny.deviantart.com    =
#   Github    : https://github.com/ilnanny      =
#================================================
#================================================

echo "GTK2 VERSION :"
pkg-config --modversion gtk+-2.0
echo "#==============================="
echo "GTK3 VERSION :"
pkg-config --modversion gtk+-3.0
echo "#==============================="
echo "Close your Terminal to exit "
read
