#!/bin/bash
#=================================================
#=================================================
#=   O.S.      : Gnu Linux                       =
#=   Author    : Cristian Pozzessere   = ilnanny =
#=   D.A.Page  : http://ilnanny.deviantart.com   =
#=   Github    : https://github.com/ilnanny      =
#=================================================
# Richiede il software lshw
#=================================================
set -o errexit
[[ $(whoami) == 'root' ]] || exec sudo su -c $0 root
#=
yellow='\033[01;33m'
blue='\033[01;34m'
clear
#=====================================================================

printf "${yellow}Di seguito tutti i drivers installati nel Sistema${blue}\n"
lshw | grep -i driver | perl -pe 's/^.*driver=(\S+).*$/$1/g;' | sort -u

printf "${yellow}Fatto, chiudi il terminale!\n"
exit 4


















































































































