#!/bin/bash
#================================================
#================================================
#   O.S.      : Gnu Linux                       =
#   Author    : Cristian Pozzessere   = ilnanny =
#   D.A.Page  : http://ilnanny.deviantart.com   =
#   Github    : https://github.com/ilnanny      =
#================================================
#================================================

take_ss() {
	sleep 5 && scrot 'ilnanny_%Y-%m-%d_%k-%M-%S_$wx$h.png' -e 'mv $f ~/Immagini/' "$1"
}

notify_send() {
	notify-send --expire-time=2000 -i view-fullscreen 'Screenshot!!' 'Salvato in  ~/Immagini/' && sleep 0.5
}

main() {
	case "$1" in
		-c)
			take_ss -s
			notify_send
			;;
		*)
			notify_send
			take_ss
	esac
}

main "$@"
