#!/bin/bash
#================================================
#================================================
#   O.S.      : Gnu Linux                       =
#   Author    : Cristian Pozzessere   = ilnanny =
#   D.A.Page  : http://ilnanny.deviantart.com   =
#   Github    : https://github.com/ilnanny      =
#================================================
#================================================
echo "__________________________________________"
echo "                                          "
echo "  Devi aver Installato il pacchetto Ntp   "
echo "__________________________________________"
sudo ntpdate it.pool.ntp.org
exit
