#!/bin/bash
#================================================
#================================================
#   O.S.      : Gnu Linux                       =
#   Author    : Cristian Pozzessere   = ilnanny =
#   D.A.Page  : http://ilnanny.deviantart.com   =
#   Github    : https://github.com/ilnanny      =
#================================================
# genera una password di 8 caratteri casuali
#================================================
echo "Ecco la nuova Password generata :"
echo ""
egrep -ioam1 '[a-zA-Z0-9]{8}' /dev/urandom
echo ""
echo "Chiudi Il Terminale."
read
