#!/bin/bash
#================================================
#================================================
#   O.S.      : Gnu Linux                       =
#   Author    : Cristian Pozzessere   = ilnanny =
#   D.A.Page  : http://ilnanny.deviantart.com    =
#   Github    : https://github.com/ilnanny      =
#================================================
#================================================
set -o errexit
[[ $(whoami) == 'root' ]] || exec sudo su -c $0 root
#===========
sudo mount -o remount /dev/sdc1 /media/Dati
#sudo mount -o remount /dev/sdd1 /media/500GB
exit 0
