#!/bin/bash
#================================================
#================================================
#   O.S.      : Gnu Linux                       =
#   Author    : Cristian Pozzessere   = ilnanny =
#   D.A.Page  : http://ilnanny.deviantart.com   =
#   Github    : https://github.com/ilnanny      =
#================================================
#
# Richiede il software ffmpeg
#
# Registro un video con estensione 'avi' con il codec 'libx264'
# con una risoluzione di 1920x1080 a 60 frame per secondo.
echo ="================================================"
echo ="  Per Fermare la registrazione premi CTRL+CANC  "
echo ="================================================"
sleep 2
ffmpeg -f x11grab -r 60 -s 1920x1080 -i :0.0 -vcodec libx264 /tmp/screencast.avi
echo ="================================================"
echo ="      Ecco il tuo video salvato in   /tmp       "
echo ="================================================"
sleep 1
thunar /tmp


