#!/bin/bash
#================================================
#================================================
#   O.S.      : Gnu Linux                       =
#   Author    : Cristian Pozzessere   = ilnanny =
#   D.A.Page  : http://ilnanny.deviantart.com    =
#   Github    : https://github.com/ilnanny      =
#================================================
#Registra uno screencast in mpeg in /tmp/:
#================================================
#
ffmpeg -f x11grab -s 1920x1080 -i :0.0 /tmp/screencast.mpg
echo ="================================================"
echo ="     Il tuo video è stato slavato in /tmp       "
echo ="================================================"
