#!/bin/bash
#================================================
#================================================
#   O.S.      : Gnu Linux                       =
#   Author    : Cristian Pozzessere   = ilnanny =
#   D.A.Page  : http://ilnanny.deviantart.com   =
#   Github    : https://github.com/ilnanny      =
#================================================
# Progect   : Cercatutti gli script nel sistema
# e gli salva in una lista nella Home utente.                               =
#================================================
#Imposta l'utente Root
#set -o errexit
#[[ $(whoami) == 'root' ]] || exec sudo su -c $0 root
for i in $( echo $PATH | sed 's/:/\ /g' ); do for a in $i/*; do if [[ -f $a ]] && [[ -r $a ]]; then if [[ "x$( cat $a | grep "#\!/bin/bash" )" != "x" ]] || [[ "x$( cat $a | grep "#\!/bin/sh" )" != "x" ]]; then echo $a && echo $a >> /home/$USER/lista.sh; fi; fi; done; done
exit 0
