#!/usr/bin/env bash
#================================================
#================================================
#   O.S.      : Gnu Linux                       =
#   Author    : Cristian Pozzessere   = ilnanny =
#   D.A.Page  : http://ilnanny.deviantart.com   =
#   Github    : https://github.com/ilnanny      =
#================================================
#================================================
# Traduzione testi offline 
# required : xsel,zenity,
#================================================
text="$(in-o)"
translate="$(wget -U "Mozilla/5.0" -qO - "http://translate.googleapis.com/translate_a/single?client=gtx&sl=auto&tl=en&dt=t&q=$(echo $text | sed "s/[\"'<>]//g")" | sed "s/,,,0]],,.*//g" | awk -F'"' '{print $2, $6}')"
echo -e "Testo :  " "$text"'\n' > /tmp/notitrans
echo "Tradotto :  " "$translate" >> /tmp/notitrans
zenity --text-info --title="Traduzione" --filename=/tmp/notitrans
