#!/bin/bash
#================================================
#================================================
#   O.S.      : Gnu Linux                       =
#   Author    : Cristian Pozzessere   = ilnanny =
#   D.A.Page  : http://lnanny.deviantart.com    =
#   Github    : https://github.com/ilnanny      =
#================================================
#================================================
yellow='\033[01;33m'
blue='\033[01;34m'
clear
if [ "$(whoami)" != "root" ] || \
( [ $# -ge 1 ] && ( [ "$1" != "true" ] && [ "$1" != "false" ] && [ "$1" != "usb" ] ))
then
printf "${blue}
===========================   LEGENDA    =============================\n"
printf "${yellow}
  sudo $0             # elenca tutte le unità

  sudo $0 usb         # elenca le unità USB
\n"
printf "${blue}======================================================================\n"
printf "${yellow}
  Formatta la pendrive in fat32

  mkfs.vfat -n chiavetta -I /dev/sd..
\n"
printf "${blue}======================================================================\n"
 exit
fi

if [ "$1" == "usb" ]
then
 switch=true
else
 switch="$1"
fi

# parametro $1 solo per USB (vero /falso)

cnt1=0
cnt2=0

tmpfil=$(mktemp)
ls -l /dev/disk/by-id| grep [a-z]$|tr -s ' ' ' '|cut -d ' ' -f 9,11 \
|sort -k2|grep -e \^a -e \^u|sed 's#../..#/dev#' > "$tmpfil"

#cat "$tmpfil"

while read name device
do
 cnt1=$(($cnt1 + 1))
 nam1[$cnt1]="${name%_*}"
nam1[$cnt1]=${nam1[$cnt1]:0:36}
 dev1[$cnt1]="$device"
# /bin/echo -e "${nam1[$cnt1]}\0011${dev1[$cnt1]}"
done < "$tmpfil"

sudo lsblk -db|grep disk|tr -s ' ' ' '| cut -d ' ' -f1-4 |sort > "$tmpfil"

while read device dum1 dum2 bytesize
do
 cnt2=$(($cnt2 + 1))
 dev2[cnt2]="$device"
 mbsize=$((($bytesize+500000)/1000000))
 gbsize=$((($bytesize+500000000)/1000000000))
 if [ $mbsize -lt 32000 ]
 then
  prsize[$cnt2]="${mbsize}MB"
 else
  prsize[$cnt2]="${gbsize}GB"
 fi
 device[$cnt2]="/dev/$device"
# echo "${device[$cnt2]}" "${prsize[$cnt2]}"
done < "$tmpfil"

rm "$tmpfil"

if [ $cnt1 -ge $cnt2 ]
then
 count=$cnt1
else
 count=$cnt2
fi
strsize=0
for (( i=1; i<=$count ; i++ ))
do
 if [ ${#nam1[$i]} -gt $strsize ]
 then
  strsize=${#nam1[$i]}
 fi
done
#echo $strsize
for (( i=1; i<=$count ; i++ ))
do
 addsize=$(($strsize - ${#nam1[$i]}))
 blank='                                                    '
 spacer=${blank:0:$addsize}
# echo $addsize
# echo "xxx${blank:0:$addsize}xxx"

 printsize=
 for (( j=1; j<=$count ; j++ ))
 do
#  echo "${dev1[$i]} ?==?  /dev/${dev2[$j]}"
  if [ "${dev1[$i]}" ==  "/dev/${dev2[$j]}" ]
  then
   printsize="${prsize[$j]}"
#   echo "printsize=$printsize"
  fi
 done

 if [ "$printsize" != "" ]
 then
  string="Name: ${nam1[$i]}${spacer}  Dev: ${dev1[$i]}  Size: $printsize"
  if [ "$switch" == "true" ]
  then
   usbstring="${string/Name\:\ usb\-/USB: }"
   if [ "$usbstring" != "$string" ]
   then
    /bin/echo -e "$usbstring"
   fi
  else
    /bin/echo -e "$string"
  fi
 fi
done
#
#
echo "
=======================    LEGENDA    =================================

   sudo $0             # elenca tutte le unità
   sudo $0 false       # elenca tutte le unità
   sudo $0 true        # elenca le unità USB
   sudo $0 usb         # elenca le unità USB
=======================================================================
   Formatta la pendrive in fat32
   mkfs.vfat -n chiavetta -I /dev/sd..
=======================================================================
"
