#!/bin/bash
#================================================
#================================================
#   O.S.      : Gnu Linux                       =
#   Author    : Cristian Pozzessere   = ilnanny =
#   D.A.Page  : http://ilnanny.deviantart.com   =
#   Github    : https://github.com/ilnanny      =
#================================================
#
set -o errexit
[[ $(whoami) == 'root' ]] || exec sudo su -c $0 root
printf "${GREEN}Aggiungo l'utente a Sudoers\n"
echo 'frozen-files="/etc/sudoers"' >> /etc/dispatch-conf.conf
sed -i "s/# %wheel ALL=(ALL) NOPASSWD: ALL/%wheel ALL=(ALL) NOPASSWD: ALL/" /etc/sudoers
chsh -s /bin/bash ilnanny
printf "${GREEN}Aggiungo l'utente ilnanny ai gruppi più usati\n"
gpasswd -a ilnanny adbusers
gpasswd -a ilnanny adm
gpasswd -a ilnanny audio
gpasswd -a ilnanny avahi
gpasswd -a ilnanny bluetooth
gpasswd -a ilnanny cdemu
gpasswd -a ilnanny cdrom
gpasswd -a ilnanny cdrw
gpasswd -a ilnanny disk
gpasswd -a ilnanny floppy
gpasswd -a ilnanny games
gpasswd -a ilnanny gdm
gpasswd -a ilnanny ilnanny
gpasswd -a ilnanny lightdm
gpasswd -a ilnanny locate.mpd
gpasswd -a ilnanny lpadmin
gpasswd -a ilnanny lxdm
gpasswd -a ilnanny mlocate
gpasswd -a ilnanny netdev
gpasswd -a ilnanny networkmanager
gpasswd -a ilnanny ntp
gpasswd -a ilnanny plugdev
gpasswd -a ilnanny polkitd
gpasswd -a ilnanny scanner
gpasswd -a ilnanny shadow
gpasswd -a ilnanny ssh
gpasswd -a ilnanny sudo
gpasswd -a ilnanny sudoers
gpasswd -a ilnanny sys
gpasswd -a ilnanny tape
gpasswd -a ilnanny tty
gpasswd -a ilnanny usb
gpasswd -a ilnanny vboxusers
gpasswd -a ilnanny video
gpasswd -a ilnanny wheel
gpasswd -a root    gdm
gpasswd -a root    lightdm
gpasswd -a root    lxdm
gpasswd -a root    slim
gpasswd -a root    sddm

exit 0
