#!/bin/bash
#================================================
#================================================
#   O.S.      : Gnu Linux                       =
#   Author    : Cristian Pozzessere   = ilnanny =
#   D.A.Page  : http://ilnanny.deviantart.com   =
#   Github    : https://github.com/ilnanny      =
#================================================
#
find . -name '*.svg' -exec xmllint --noout {} + 2> xmlerrors
if [ -s xmlerrors ]; then
    cat xmlerrors
    rm xmlerrors
    exit 1
fi
