#!/bin/bash
#================================================
#================================================
#   O.S.      : Gnu Linux                       =
#   Author    : Cristian Pozzessere   = ilnanny =
#   D.A.Page  : http://ilnanny.deviantart.com   =
#   Github    : https://github.com/ilnanny      =
#================================================
#               Virtualbox ,Moduli Kernel.
#================================================
set -o errexit
[[ $(whoami) == 'root' ]] || exec sudo su -c $0 root
#
yellow='\033[01;33m'
blue='\033[01;34m'
clear
#===================================================================#

printf "${yellow}Attivo i moduli Kernel per VirtualBox \n"
modprobe vboxdrv
modprobe vboxnetadp
modprobe vboxnetflt
modprobe vboxpci
printf "${blue}Fatto, chiudi il terminale.\n"
exit 4


















































































































