#!/bin/bash
#_______________________________________________=
#   O.S.      : Gnu Linux                       =
#   Author    : Cristian Pozzessere < ilnanny > =
#   D.A.Page  : http://ilnanny.deviantart.com   =
#   Github    : https://github.com/ilnanny      =
#_______________________________________________=
#Imposta l'utente Root
set -o errexit
[[ $(whoami) == 'root' ]] || exec sudo su -c $0 root
#____________________________________________________=

find . -type f -name "*.sw[klmnop]" -delete

find . -type f \( -name ".*.s[a-v][a-z]" -o -name ".*.sw[a-p]" \) -delete

find . -type f -name ".*.sw[klmnop]" -delete

exit




































































































