#!/bin/bash
#================================================
#================================================
#   O.S.      : Gnu Linux                       =
#   Author    : Cristian Pozzessere   = ilnanny =
#   D.A.Page  : http://ilnanny.deviantart.com    =
#   Github    : https://github.com/ilnanny      =
#================================================
#================================================
mmaker -v OpenBox3

su -c "cp .config/openbox/menu.xml /etc/xdg/openbox/menu.xml"
echo "Il menu di OpenBox è stato rigenerato con tutti i programmi"
exit
