#!/bin/bash
#================================================
#================================================
#   O.S.      : Gnu Linux                       =
#   Author    : Cristian Pozzessere   = ilnanny =
#   D.A.Page  : http://ilnanny.deviantart.com   =
#   Github    : https://github.com/ilnanny      =
#================================================
# Visualizza data e ora in un popup di dunst
#richiede 'dunst'
#================================================
tgl=$(date +'%a %d %b')
jam=$(date +'%H:%M')

notify-send "$tgl" "$jam"
