#!/bin/bash
#================================================
#================================================
#   O.S.      : Gnu Linux                       =
#   Author    : Cristian Pozzessere   = ilnanny =
#   D.A.Page  : http://ilnanny.deviantart.com    =
#   Github    : https://github.com/ilnanny      =
#================================================
#================================================
set -o errexit
[[ $(whoami) == 'root' ]] || exec sudo su -c $0 root
xrandr --newmode "1920x1080_60.00"  108.88  1280 1360 1496 1712  1024 1025 1028 1060  -HSync +Vsync
xrandr --addmode DVI-0 1920x1080_60.00
xrandr --output DVI-0 --mode 1920x1080_60.00

exit 0





















































































































