#!/usr/bin/env bash

#================================================

readonly TITLE="Tint2 Edit"
readonly CHECKLIST="zenity --width=400 --height=500 $ICON --list --checklist --multiple"
readonly TPATH="$HOME/.config/tint2"
readonly FILES=($(find "$TPATH" -maxdepth 4 -type f))


case "$@" in
    -h|--help) echo -e "$HELP" ; exit 0
esac

edit_Configs() {
    for file in "${FILES[@]}"; do
        NAME=$(basename "$file")
        if grep -q "panel_monitor" "$file" || [[ $NAME = *tint2rc ]] || [[ $NAME == 'tint2rc' ]]; then
            LIST="$LIST FALSE $NAME"
            ARRAY+=("$file")
        fi
    done
    MSG="<big>Seleziona il tint2 config da editaret</big>\n\n"
    ANSWER=$($CHECKLIST --title="$TITLE" --text="$MSG" --column="Select" --column="Name" $LIST --separator=" ")
    if [[ $? == 1 ]]; then
        exit 0
    else
        for name in $ANSWER; do
            for file in "${ARRAY[@]}"; do
                if [[ $(basename "$file") == "$name" ]]; then
                    if hash exo-open &>/dev/null; then
                        (exo-open "$file" &) ; break
                    elif hash termite &>/dev/null; then
                        (termite -e "$EDITOR $file" &>/dev/null) ; break
                    elif hash st &>/dev/null; then
                        (st -e $EDITOR $file &) ; break
                    elif hash urxvt &>/dev/null; then
                        (urxvt -e "$EDITOR $file" &) ; break
                    fi
                fi
            done
        done
    fi
}

edit_Configs

exit 0
