#!/usr/bin/env bash
#================================================
#================================================
#   O.S.      : Gnu Linux                       =
#   Author    : Cristian Pozzessere   = ilnanny =
#   D.A.Page  : http://ilnanny.deviantart.com   =
#   Github    : https://github.com/ilnanny      =
#================================================
# Traduce il testo selezionato in una finestra
# dipendenze: xsel,zenity
# shortcut :barra-spaziatrice+t
#================================================

text="$(xsel -o)"
translate="$(wget -U "Mozilla/5.0" -qO - "http://translate.googleapis.com/translate_a/single?client=gtx&sl=auto&tl=it&dt=t&q=$(echo $text | sed "s/[\"'<>]//g")" | sed "s/,,,0]],,.*//g" | awk -F'"' '{print $2, $6}')"
echo -e "Testo Originale:" "$text"'\n' > /tmp/notitrans
echo "Traduzione:" "$translate" >> /tmp/notitrans
zenity --text-info --title="Traduzione" --filename=/tmp/notitrans
