#!/bin/bash
#================================================
#================================================
#   O.S.      : Gnu Linux                       =
#   Author    : Cristian Pozzessere   = ilnanny =
#   D.A.Page  : http://lnanny.deviantart.com    =
#   Github    : https://github.com/ilnanny      =
#================================================
#================================================
sudo ntpdate it.pool.ntp.org
sudo emerge --sync
sudo emerge -uDN world
sudo emerge -uDN system
sudo emerge --depclean
sudo rm -fr /tmp/* 
sudo rm -rfv ~/.cache ~/.local/share/Trash ~/.thumbnails
rm -fr /tmp/* 
rm -rfv ~/.cache ~/.local/share/Trash ~/.thumbnails
exit 0
