#!/usr/bin/env bash


#================================================
#
#  To start the default conky session at login, add the following line
#  to config/openbox/autostart:
#     (sleep 2s && conky-session --autostart) &

readonly CPATH="$HOME/.config/conky"

readonly ICON="/usr/share/icons/48x48.png"

readonly DLG="zenity --question --width=220 --height=120 --window-icon=$ICON"

# mutable session file
SESSIONFILE="$CPATH/conky-sessionfile"

findArgs() {
    local i=0
    for arg in "$@";do
        if [[ $arg = "--default" ]]; then
            arg=$SESSIONFILE
        fi
        if [[ $arg = "--autostart" ]]; then
            NOKILL=1
        fi
        if [[ -f $arg ]]; then
            rawArr[$i]=$arg
            i=$((i + 1))
        fi
    done
    if [[ ${#rawArr[@]} != 0 ]]; then
        sessArr=($(printf "%s\n" "${rawArr[@]}" | sort -u))
        if [[ $NOKILL = 0 ]]; then
            killConkys
        fi
        for SESSION in "${sessArr[@]}"; do
            source "$SESSION"
        done
    else
        if [[ -f $SESSIONFILE ]] && [[ $NOKILL == 1 ]]; then
            source "$SESSIONFILE"
        else
            echo -e "ERROR: sessionfile \"$SESSIONFILE\" not found. Using default"
            conky -c "$CPATH/.conkyrc"
            exit 0
        fi
    fi
}

killConkys() {
    if [[ $(pidof conky) ]]; then
        if $DLG --title=" Conky Session" --text="<big>Kill running conkys first?</big>" &>/dev/null; then
            killall conky ; sleep 0.2s
        fi
    fi
}

NOKILL=0
if [[ $# == 0 ]]; then
    killConkys
    if ! [[ -f "$SESSIONFILE" ]]; then
        echo -e "ERROR: sessionfile \"$SESSIONFILE\" not found. Using default" ; conky -c "$CPATH/.conkyrc" ; exit 0
    else
        source "$SESSIONFILE"
    fi
elif [[ $1 = "-h" ]] || [[ $1 = "--help" ]]; then
    echo -e "$USAGE" ; exit 0
else
    findArgs "$@"
fi

exit 0
