#!/usr/bin/env bash
#================================================
#================================================
#   O.S.      : Gnu Linux                       =
#   Author    : Cristian Pozzessere   = ilnanny =
#   D.A.Page  : http://ilnanny.deviantart.com   =
#   Github    : https://github.com/ilnanny      =
#================================================
# ConkyChoose based to conkizen-bunselabs
#================================================

readonly CZEN="ConkyChoose"
readonly CSESSION="conky-session"
readonly CONKYDEFAULT="$HOME/.conkyrc"
readonly CONKYPATH="$HOME/.conky/"
readonly CSESSIONFILE="$CONKYPATH/conky-sessionfile"
readonly SESSIONS="$CONKYPATH/saved-sessions"

for arg in "$@"; do
    case $arg in
        -h|--help) echo -e "$HELP" ; exit 0
    esac
done

if ! . "/usr/lib/common/include.cfg" 2>/dev/null; then
    echo "Error: Failed to source /usr/lib/common/include.cfg" ; exit 1
fi

if ! [[ -e $CSESSIONFILE ]]; then
    echo "Error: Failed to locate conky-sessionfile in $CONKYPATH" >&2
    echo "conky -c $CONKYPATH/.conkyrc & sleep 1" > "$CSESSIONFILE"
fi

if ! [[ -e $SESSIONS ]]; then
    echo "$0: Failed to locate saved-sessions in $CONKYPATH" >&2
fi

declareDependencies zenity

getSessions(){
    menuItem "Default" "$CSESSION $CSESSIONFILE"
    if [[ -e $SESSIONS ]]; then
        while read -r session ; do
            [[ -z $session ]] && continue
            menuItem "$session" "$CSESSION $session"
        done < "$SESSIONS"
    fi
}

loadChooserMenu(){
    if type "$CZEN" &>/dev/null; then
        menuItem "Conky Chooser" "$CZEN"
    fi
}

loadNewsessionMenu(){
    if type "$CZEN" &>/dev/null; then
        menuItem "New Conky Session" "$CZEN -z"
    fi
}

loadReloadMenu(){
    if type "$CSESSION" &>/dev/null; then
        menuItem "Reload Conkys" "$CSESSION"
    fi
}

loadSavedsessionSubmenu(){
    if type "$CSESSION" &>/dev/null; then
        menuSubmenu "Sessions" "Saved Sessions"
        getSessions
        menuSubmenuEnd
    fi
}

loadPinMenu(){
    if type conkypin &>/dev/null; then
        menuItem "Pin moveable Conkys" "conkypin"
        menuSeparator
    fi
}

loadEditMenu(){
    if hash exo-open &>/dev/null; then
        menuItem "Default conkyrc" "exo-open $CONKYDEFAULT"
    else
        menuItem "Default conkyrc" "termite -e $EDITOR $CONKYDEFAULT"
    fi
    if [[ $(pidof conky) ]]; then
        menuSubmenu "RunningConky" "Running Conkys"
        while read -r session; do
            [[ -z $session ]] && continue
            CPATH=$(awk '{print $3}' <<< "$session")
            CONKY=$(awk -F"/" '{print $(NF-1)"/"$NF }' <<< "$CPATH")
            if hash exo-open &>/dev/null; then
                menuItem "$CONKY" "exo-open $CPATH"
            else
                menuItem "$CONKY" "termite -e '$EDITOR $CPATH'"
            fi
        done < "$CSESSIONFILE"
        menuSubmenuEnd
    else
        menuItem "No Running Conkys"
    fi
}

getConkys(){
    menuSubmenu "EditConky" "Edit Conkys"
    if type conkyedit &>/dev/null;then
        menuItem "Conky Editor" "conkyedit"
        loadEditMenu
    else
        loadEditMenu
    fi
    menuSubmenuEnd
}

checkHelpfile(){
    DLG="zenity --text-info --title='Conky Chooser Help' --filename=$HELPFILE --width=650 --height=700 &>/dev/null"
    if [[ -e $HELPFILE ]];then
        menuItem "Conky Chooser Help" "$DLG"
    fi
}

menuStart "Conkymenu" "Conky"
loadChooserMenu
loadReloadMenu
getConkys
menuSeparator
loadPinMenu
loadNewsessionMenu
loadSavedsessionSubmenu
menuSeparator
checkHelpfile
menuEnd
